### ISSUE TITLE
I find an error in BitConvert>ToUInt32

### ISSUE THREAD

**Issue by ryansix** [bouyeijiang/Beidou-Gps#1]
`if (isBigEndian)
            {
                return (((UInt32)value[offset] << 24)
                   | ((UInt32)value[offset + 1] << 16)
                   | ((UInt32)value[offset + 2] << 8)
                   | value[ 3]);
            }`
should  be 
`if (isBigEndian)
            {
                return (((UInt32)value[offset] << 24)
                   | ((UInt32)value[offset + 1] << 16)
                   | ((UInt32)value[offset + 2] << 8)
                   | value[offset + 3]);
            }`

**Comment by bouyeijiang** [comment]
yeah
